### PR TITLE
Add persistent storage through helm charts

### PR DESCRIPTION
**Pull request by foxycoder**
- [x] Refactor storage values like we do it in [Alea](https://github.com/Codaisseur/alea/blob/master/charts/alea/values.yaml)
- [x] Create a [SSD](https://github.com/Codaisseur/alea/blob/master/charts/alea/templates/ssd-storage-class.yaml) and a [Normal](https://github.com/Codaisseur/alea/blob/master/charts/alea/templates/standard-storage-class.yaml) storage class
- [x] Create the Mongo [volume](https://github.com/Codaisseur/alea/blob/master/charts/alea/templates/mongodb-storage-volume.yaml) and [claim](https://github.com/Codaisseur/alea/blob/master/charts/alea/templates/mongodb-storage-claim.yaml)

### CODE REVIEW

**Comment by michfarr** [comment]
Ticked the boxes: added the ssd and standard storage classes, along with mongo persistent volume and persistent claim, as well as refactoring the values.yaml to keep the templates DRY.  I also removed the create_storage bash script since it is now redundant.

**Comment by michfarr** [comment]
I've merged master to this feature branch to incorporate and refactor the node-runner deployment and service.  As well, I renamed dev.yaml to dev-settings and updated the bin/install bash script accordingly.

**Comment by michfarr** [comment]
@foxycoder Do we want to remove the "coderunner-" prefix from what the coderunner-ruby and coderunner-node deployments to allow us to use ruby.coderunner:port/ and node.coderunner:port/ instead of coderunner-{language}.coderunner:port/?

**Comment by foxycoder** [comment]
Yes :)

**Pull request merged**
